name: Erlang CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: erlang:23

    steps:
    - uses: actions/checkout@v1

    - name: Compile
      run: make deps app
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

    - name: Run tests
      env:
        COVER: "1"
      run: |
        make tests

        # Covert coverage data to XML
        ./bin/covertool -cover cover/ct.coverdata -output cover/cover.ct.xml
        ./bin/covertool -cover cover/eunit.coverdata -output cover/cover.eunit.xml

    - name: Upload CT test coverage data to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: ct
        file: "./cover/cover.ct.xml"

    - name: Upload eunit test coverage data to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: eunit
        file: "./cover/cover.eunit.xml"

  lint:
    runs-on: ubuntu-latest
    container:
      image: erlang:23

    steps:
    - uses: actions/checkout@v1

    - name: Compile
      run: make deps app
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

    - name: elvis
      run: make elvis

    - name: Dialyze
      run: make dialyze
